### PR TITLE
Refactor for multilanguage support

### PR DESCRIPTION
**Pull request by lmaczulajtys**
Refactor for future development in #94

### CODE REVIEW

**Comment by alxwrd** [comment]
hi @lmaczulajtys, thanks for this :tada: 

Would it be possible to remove the language parameter for `syllable_count()` and have it use the new `.__lang` property?

```python
    def syllable_count(self, text):
        ...
        dic = Pyphen(lang=self.__lang)
```

**Comment by lmaczulajtys** [comment]
Done. This change breaks reverse compatibility for `syllable_count`.

**Comment by alxwrd** [comment]
@lmaczulajtys good point. I've just added the argument back in with a warning for using it.

**Comment by alxwrd** [comment]
Thanks for this 🎉

**Pull request merged**
